export default {
  ACTIVE_PRICE: "ACTIVE_PRICE",
  ACTIVE_TOP: "ACTIVE_TOP",
  ACTIVE_POPULAR: "ACTIVE_POPULAR",
  ACTIVE_DIET: "ACTIVE_DIET",
  PRICE_1: "PRICE_1",
  PRICE_2: "PRICE_2",
  PRICE_3: "PRICE_3",
  TOP: "TOP",
  POPULAR: "POPULAR",
  DIET: "DIET",
  RESET: "RESET",
};
